version: "3.8"
services:
  app:
    build:
      args:
        user: isx
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app-0.1
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www

  db:
    image: mysql:5.7.29
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8001:8080
